// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: river_workflow_signal.sql

package dbsqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const workflowSignalEmit = `-- name: WorkflowSignalEmit :one
INSERT INTO /* TEMPLATE: schema */river_workflow_signal (
    workflow_id,
    signal_key,
    payload,
    idempotency_key,
    source,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6::timestamptz
)
ON CONFLICT (workflow_id, idempotency_key) WHERE idempotency_key IS NOT NULL DO NOTHING
RETURNING id, workflow_id, signal_key, payload, idempotency_key, source, created_at, resolved_at
`

type WorkflowSignalEmitParams struct {
	WorkflowID     string
	SignalKey      string
	Payload        []byte
	IdempotencyKey pgtype.Text
	Source         pgtype.Text
	Now            time.Time
}

func (q *Queries) WorkflowSignalEmit(ctx context.Context, db DBTX, arg *WorkflowSignalEmitParams) (*RiverWorkflowSignal, error) {
	row := db.QueryRow(ctx, workflowSignalEmit,
		arg.WorkflowID,
		arg.SignalKey,
		arg.Payload,
		arg.IdempotencyKey,
		arg.Source,
		arg.Now,
	)
	var i RiverWorkflowSignal
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.SignalKey,
		&i.Payload,
		&i.IdempotencyKey,
		&i.Source,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return &i, err
}

const workflowSignalGetByIdempotency = `-- name: WorkflowSignalGetByIdempotency :one
SELECT id, workflow_id, signal_key, payload, idempotency_key, source, created_at, resolved_at
FROM /* TEMPLATE: schema */river_workflow_signal
WHERE workflow_id = $1
  AND idempotency_key = $2
`

type WorkflowSignalGetByIdempotencyParams struct {
	WorkflowID     string
	IdempotencyKey pgtype.Text
}

func (q *Queries) WorkflowSignalGetByIdempotency(ctx context.Context, db DBTX, arg *WorkflowSignalGetByIdempotencyParams) (*RiverWorkflowSignal, error) {
	row := db.QueryRow(ctx, workflowSignalGetByIdempotency, arg.WorkflowID, arg.IdempotencyKey)
	var i RiverWorkflowSignal
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.SignalKey,
		&i.Payload,
		&i.IdempotencyKey,
		&i.Source,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return &i, err
}

const workflowSignalList = `-- name: WorkflowSignalList :many
SELECT id, workflow_id, signal_key, payload, idempotency_key, source, created_at, resolved_at
FROM /* TEMPLATE: schema */river_workflow_signal
WHERE workflow_id = $1
  AND ($2::text IS NULL OR signal_key = $2)
  AND ($3::bool OR resolved_at IS NULL)
ORDER BY created_at, id
LIMIT $4::int
`

type WorkflowSignalListParams struct {
	WorkflowID      string
	SignalKey       pgtype.Text
	IncludeResolved pgtype.Bool
	Max             int32
}

func (q *Queries) WorkflowSignalList(ctx context.Context, db DBTX, arg *WorkflowSignalListParams) ([]*RiverWorkflowSignal, error) {
	rows, err := db.Query(ctx, workflowSignalList,
		arg.WorkflowID,
		arg.SignalKey,
		arg.IncludeResolved,
		arg.Max,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RiverWorkflowSignal
	for rows.Next() {
		var i RiverWorkflowSignal
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.SignalKey,
			&i.Payload,
			&i.IdempotencyKey,
			&i.Source,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const workflowSignalListNewest = `-- name: WorkflowSignalListNewest :many
SELECT id, workflow_id, signal_key, payload, idempotency_key, source, created_at, resolved_at
FROM /* TEMPLATE: schema */river_workflow_signal
WHERE workflow_id = $1
  AND ($2::text IS NULL OR signal_key = $2)
  AND ($3::bool OR resolved_at IS NULL)
ORDER BY created_at DESC, id DESC
LIMIT $4::int
`

type WorkflowSignalListNewestParams struct {
	WorkflowID      string
	SignalKey       pgtype.Text
	IncludeResolved pgtype.Bool
	Max             int32
}

func (q *Queries) WorkflowSignalListNewest(ctx context.Context, db DBTX, arg *WorkflowSignalListNewestParams) ([]*RiverWorkflowSignal, error) {
	rows, err := db.Query(ctx, workflowSignalListNewest,
		arg.WorkflowID,
		arg.SignalKey,
		arg.IncludeResolved,
		arg.Max,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RiverWorkflowSignal
	for rows.Next() {
		var i RiverWorkflowSignal
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.SignalKey,
			&i.Payload,
			&i.IdempotencyKey,
			&i.Source,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const workflowSignalMarkResolved = `-- name: WorkflowSignalMarkResolved :exec
UPDATE /* TEMPLATE: schema */river_workflow_signal
SET resolved_at = $1::timestamptz
WHERE workflow_id = $2
  AND signal_key = ANY($3::text[])
  AND resolved_at IS NULL
`

type WorkflowSignalMarkResolvedParams struct {
	Now        time.Time
	WorkflowID string
	SignalKeys []string
}

func (q *Queries) WorkflowSignalMarkResolved(ctx context.Context, db DBTX, arg *WorkflowSignalMarkResolvedParams) error {
	_, err := db.Exec(ctx, workflowSignalMarkResolved, arg.Now, arg.WorkflowID, arg.SignalKeys)
	return err
}
