// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: river_periodic_job.sql

package dbsqlc

import (
	"context"
	"time"
)

const periodicJobGetAll = `-- name: PeriodicJobGetAll :many
SELECT id, created_at, updated_at, next_run_at
FROM /* TEMPLATE: schema */river_periodic_job
ORDER BY id
`

func (q *Queries) PeriodicJobGetAll(ctx context.Context, db DBTX) ([]*RiverPeriodicJob, error) {
	rows, err := db.Query(ctx, periodicJobGetAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RiverPeriodicJob
	for rows.Next() {
		var i RiverPeriodicJob
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NextRunAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const periodicJobKeepAliveAndReap = `-- name: PeriodicJobKeepAliveAndReap :many
WITH touched AS (
    UPDATE /* TEMPLATE: schema */river_periodic_job
    SET updated_at = coalesce($1::timestamptz, now())
    WHERE id = ANY($2::text[])
    RETURNING id
),
reaped AS (
    DELETE FROM /* TEMPLATE: schema */river_periodic_job
    WHERE NOT (id = ANY($2::text[]))
      AND updated_at < $3::timestamptz
    RETURNING id, created_at, updated_at, next_run_at
)
SELECT id, created_at, updated_at, next_run_at FROM reaped
WHERE (SELECT count(*) FROM touched) >= 0
`

type PeriodicJobKeepAliveAndReapParams struct {
	Now          *time.Time
	ID           []string
	StaleHorizon time.Time
}

type PeriodicJobKeepAliveAndReapRow struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	NextRunAt time.Time
}

func (q *Queries) PeriodicJobKeepAliveAndReap(ctx context.Context, db DBTX, arg *PeriodicJobKeepAliveAndReapParams) ([]*PeriodicJobKeepAliveAndReapRow, error) {
	rows, err := db.Query(ctx, periodicJobKeepAliveAndReap, arg.Now, arg.ID, arg.StaleHorizon)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*PeriodicJobKeepAliveAndReapRow
	for rows.Next() {
		var i PeriodicJobKeepAliveAndReapRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NextRunAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const periodicJobUpsertMany = `-- name: PeriodicJobUpsertMany :many
INSERT INTO /* TEMPLATE: schema */river_periodic_job (
    id,
    next_run_at,
    updated_at
)
SELECT
    unnest($1::text[]),
    unnest($2::timestamptz[]),
    unnest($3::timestamptz[])
ON CONFLICT (id) DO UPDATE
SET
    next_run_at = EXCLUDED.next_run_at,
    updated_at  = EXCLUDED.updated_at
RETURNING id, created_at, updated_at, next_run_at
`

type PeriodicJobUpsertManyParams struct {
	ID        []string
	NextRunAt []time.Time
	UpdatedAt []time.Time
}

func (q *Queries) PeriodicJobUpsertMany(ctx context.Context, db DBTX, arg *PeriodicJobUpsertManyParams) ([]*RiverPeriodicJob, error) {
	rows, err := db.Query(ctx, periodicJobUpsertMany, arg.ID, arg.NextRunAt, arg.UpdatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RiverPeriodicJob
	for rows.Next() {
		var i RiverPeriodicJob
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NextRunAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
