// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: river_workflow_signal.sql

package dbsqlc

import (
	"context"
)

const workflowSignalEmit = `-- name: WorkflowSignalEmit :one
INSERT INTO /* TEMPLATE: schema */river_workflow_signal (
    workflow_id,
    signal_key,
    payload,
    idempotency_key,
    source,
    created_at
) VALUES (
    ?1,
    ?2,
    cast(?3 AS text),
    cast(?4 AS text),
    cast(?5 AS text),
    cast(?6 AS text)
)
ON CONFLICT (workflow_id, idempotency_key) WHERE idempotency_key IS NOT NULL DO NOTHING
RETURNING id, workflow_id, signal_key, payload, idempotency_key, source, created_at, resolved_at
`

type WorkflowSignalEmitParams struct {
	WorkflowID     string
	SignalKey      string
	Payload        string
	IdempotencyKey *string
	Source         *string
	Now            string
}

func (q *Queries) WorkflowSignalEmit(ctx context.Context, db DBTX, arg *WorkflowSignalEmitParams) (*RiverWorkflowSignal, error) {
	row := db.QueryRowContext(ctx, workflowSignalEmit,
		arg.WorkflowID,
		arg.SignalKey,
		arg.Payload,
		arg.IdempotencyKey,
		arg.Source,
		arg.Now,
	)
	var i RiverWorkflowSignal
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.SignalKey,
		&i.Payload,
		&i.IdempotencyKey,
		&i.Source,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return &i, err
}

const workflowSignalGetByIdempotency = `-- name: WorkflowSignalGetByIdempotency :one
SELECT id, workflow_id, signal_key, payload, idempotency_key, source, created_at, resolved_at
FROM /* TEMPLATE: schema */river_workflow_signal
WHERE workflow_id = ?1
  AND idempotency_key = cast(?2 AS text)
`

type WorkflowSignalGetByIdempotencyParams struct {
	WorkflowID     string
	IdempotencyKey string
}

func (q *Queries) WorkflowSignalGetByIdempotency(ctx context.Context, db DBTX, arg *WorkflowSignalGetByIdempotencyParams) (*RiverWorkflowSignal, error) {
	row := db.QueryRowContext(ctx, workflowSignalGetByIdempotency, arg.WorkflowID, arg.IdempotencyKey)
	var i RiverWorkflowSignal
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.SignalKey,
		&i.Payload,
		&i.IdempotencyKey,
		&i.Source,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return &i, err
}

const workflowSignalList = `-- name: WorkflowSignalList :many
SELECT id, workflow_id, signal_key, payload, idempotency_key, source, created_at, resolved_at
FROM /* TEMPLATE: schema */river_workflow_signal
WHERE workflow_id = ?1
  AND (?2 IS NULL OR signal_key = cast(?2 AS text))
ORDER BY created_at, id
LIMIT cast(?3 AS integer)
`

type WorkflowSignalListParams struct {
	WorkflowID string
	SignalKey  interface{}
	Max        int64
}

func (q *Queries) WorkflowSignalList(ctx context.Context, db DBTX, arg *WorkflowSignalListParams) ([]*RiverWorkflowSignal, error) {
	rows, err := db.QueryContext(ctx, workflowSignalList, arg.WorkflowID, arg.SignalKey, arg.Max)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RiverWorkflowSignal
	for rows.Next() {
		var i RiverWorkflowSignal
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.SignalKey,
			&i.Payload,
			&i.IdempotencyKey,
			&i.Source,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
