// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: river_periodic_job.sql

package dbsqlc

import (
	"context"
)

const periodicJobGetAll = `-- name: PeriodicJobGetAll :many
SELECT id, created_at, updated_at, next_run_at
FROM /* TEMPLATE: schema */river_periodic_job
ORDER BY id
`

func (q *Queries) PeriodicJobGetAll(ctx context.Context, db DBTX) ([]*RiverPeriodicJob, error) {
	rows, err := db.QueryContext(ctx, periodicJobGetAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RiverPeriodicJob
	for rows.Next() {
		var i RiverPeriodicJob
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NextRunAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const periodicJobKeepAlive = `-- name: PeriodicJobKeepAlive :exec
UPDATE /* TEMPLATE: schema */river_periodic_job
SET updated_at = coalesce(cast(?1 AS text), datetime('now', 'subsec'))
WHERE id IN (SELECT value FROM json_each(cast(?2 AS blob)))
`

type PeriodicJobKeepAliveParams struct {
	Now     *string
	IdsJson []byte
}

func (q *Queries) PeriodicJobKeepAlive(ctx context.Context, db DBTX, arg *PeriodicJobKeepAliveParams) error {
	_, err := db.ExecContext(ctx, periodicJobKeepAlive, arg.Now, arg.IdsJson)
	return err
}

const periodicJobReap = `-- name: PeriodicJobReap :many
DELETE FROM /* TEMPLATE: schema */river_periodic_job
WHERE id NOT IN (SELECT value FROM json_each(cast(?1 AS blob)))
  AND updated_at < cast(?2 AS text)
RETURNING id, created_at, updated_at, next_run_at
`

type PeriodicJobReapParams struct {
	IdsJson      []byte
	StaleHorizon string
}

func (q *Queries) PeriodicJobReap(ctx context.Context, db DBTX, arg *PeriodicJobReapParams) ([]*RiverPeriodicJob, error) {
	rows, err := db.QueryContext(ctx, periodicJobReap, arg.IdsJson, arg.StaleHorizon)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RiverPeriodicJob
	for rows.Next() {
		var i RiverPeriodicJob
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NextRunAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const periodicJobUpsert = `-- name: PeriodicJobUpsert :one
INSERT INTO /* TEMPLATE: schema */river_periodic_job (
    id,
    next_run_at,
    updated_at
) VALUES (
    ?1,
    cast(?2 AS text),
    cast(?3 AS text)
)
ON CONFLICT (id) DO UPDATE
SET
    next_run_at = EXCLUDED.next_run_at,
    updated_at  = EXCLUDED.updated_at
RETURNING id, created_at, updated_at, next_run_at
`

type PeriodicJobUpsertParams struct {
	ID        string
	NextRunAt string
	UpdatedAt string
}

func (q *Queries) PeriodicJobUpsert(ctx context.Context, db DBTX, arg *PeriodicJobUpsertParams) (*RiverPeriodicJob, error) {
	row := db.QueryRowContext(ctx, periodicJobUpsert, arg.ID, arg.NextRunAt, arg.UpdatedAt)
	var i RiverPeriodicJob
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextRunAt,
	)
	return &i, err
}
